name: 'OpenCommit Action'

on:
  push:
    branches-ignore: [main, master, dev, development, release]

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          OCO_API_KEY: ${{ secrets.OCO_API_KEY }}
          OCO_MODEL: gemini-1.5-flash
          OCO_TOKENS_MAX_INPUT: 4096
          OCO_TOKENS_MAX_OUTPUT: 500
          OCO_DESCRIPTION: false
          OCO_EMOJI: false
          OCO_LANGUAGE: en
          OCO_PROMPT_MODULE: conventional-commit
